const AUTOMATION = {
  SHEETS: {
    RAW_PROJECTS: 'Raw_Executive_Projects',
    RAW_RELEASES: 'Raw_Executive_Releases',
    EXPORT_SOURCE: 'Automation_Export_Source',
    EXPORT: 'Automation_Export',
    DASHBOARD_SNAPSHOTS: 'Dashboard_Snapshots',
    DASHBOARD_CHANGES: 'Dashboard_Changes',
    DASHBOARD_OBSERVATIONS: 'Dashboard_Observations',
    TRIGGER_LOG: 'Trigger_Log',
    CONFIG: 'Config'
  },
  HEADERS: {
    EXPORT: [
      'Record Type',
      'Source Item ID',
      'Flow ID',
      'Subject',
      'Owner',
      'Status',
      'Phase',
      'Risk Level',
      'Confidence',
      'Primary Risk',
      'Next Gate',
      'Next Gate ETA',
      'Release Date',
      'Release Status',
      'Go / No-Go Required',
      'Rollback Status',
      'Impact',
      'Included Projects',
      'Known Issues',
      'Notes',
      'Channel Override',
      'Slack Thread ID',
      'Manual Review',
      'Updated At',
      'Active'
    ],
    DASHBOARD_SNAPSHOTS: [
      'Snapshot ID',
      'Snapshot At',
      'Record Type',
      'Source Item ID',
      'Flow ID',
      'State Hash',
      'State JSON'
    ],
    DASHBOARD_CHANGES: [
      'Change ID',
      'Detected At',
      'Record Type',
      'Source Item ID',
      'Flow ID',
      'Field',
      'Old Value',
      'New Value',
      'Old State Hash',
      'New State Hash',
      'Trigger Candidate',
      'Event Key',
      'Dedupe Key',
      'Processing Status',
      'Processed At',
      'Processing Error'
    ],
    DASHBOARD_OBSERVATIONS: [
      'Source Item ID',
      'Flow ID',
      'Record Type',
      'Subject',
      'State Hash',
      'State JSON',
      'Last Observed At',
      'Last Processed At',
      'Last Trigger Log ID',
      'Processing Status',
      'Processing Error'
    ],
    TRIGGER_LOG: [
      'Trigger Log ID',
      'Created At',
      'Work Item Type',
      'Flow ID',
      'Source Row Key',
      'Trigger Candidate',
      'Event Key',
      'Old State Hash',
      'New State Hash',
      'Old State Summary',
      'New State Summary',
      'Dedupe Key',
      'Hub Queue ID',
      'Processing Status',
      'Processed At',
      'Processing Error'
    ],
    CONFIG: ['Key', 'Value']
  },
  OPTIONAL_EXPORT_HEADERS: [
    'Primary Target'
  ],
  CONFIG_ROWS: [
    ['LEADERSHIP_SPREADSHEET_ID', ''],
    ['HUB_SPREADSHEET_ID', ''],
    ['CREATE_HUB_DRAFTS', 'FALSE'],
    ['MIN_ACTIVE_EXPORT_ROWS', '1'],
    ['EXPORT_ERROR_SCAN_ROWS', '5'],
    ['RETENTION_DAYS', '60'],
    ['GC_EVERY_N_POLLS', '100'],
    ['LAST_GC_AT', ''],
    ['POLL_COUNT', '0'],
    ['GATE_APPROACHING_DAYS', '14']
  ]
};
