const AUTOMATION = {
  SHEETS: {
    PROJECTS: 'Projects_Normalized',
    GATES: 'Gates_Normalized',
    RELEASES: 'Releases_Normalized',
    SNAPSHOTS: 'Snapshots',
    TRIGGER_LOG: 'Trigger_Log',
    CONFIG: 'Config'
  },
  HEADERS: {
    PROJECTS: [
      'Work Item Type',
      'Source Spreadsheet ID',
      'Source Sheet',
      'Source Row',
      'Source Row Key',
      'Flow ID',
      'Project',
      'Lead PM',
      'Owner',
      'Current Phase',
      'Normalized Phase',
      'User Exposure',
      'Progress %',
      'Status',
      'Normalized Status',
      'Confidence of Owner (1-10)',
      'IT Risk Level',
      'Primary Risk',
      'Next Major Gate',
      'Next Gate ETA',
      'Primary Target',
      'Release Date',
      'Release Status',
      'Current State Hash',
      'Previous State Hash',
      'Last Seen At',
      'Last Processed At',
      'Trigger Candidate',
      'Communication Event',
      'Dedupe Key',
      'Hub Queue ID',
      'Processing Status',
      'Processing Error'
    ],
    GATES: [
      'Work Item Type',
      'Source Spreadsheet ID',
      'Source Sheet',
      'Source Row',
      'Source Row Key',
      'Flow ID',
      'Project',
      'Gate',
      'Target Date',
      'Actual Date',
      'Gate Status',
      'Normalized Gate Status',
      'Previous Gate Status',
      'Days Until Target',
      'Is Gate Approaching',
      'Is Gate Missed',
      'Current State Hash',
      'Previous State Hash',
      'Last Seen At',
      'Last Processed At',
      'Trigger Candidate',
      'Communication Event',
      'Dedupe Key',
      'Hub Queue ID',
      'Processing Status',
      'Processing Error'
    ],
    RELEASES: [
      'Work Item Type',
      'Source Spreadsheet ID',
      'Source Sheet',
      'Source Row',
      'Source Row Key',
      'Flow ID',
      'Release ID',
      'Project',
      'Release Date',
      'Type',
      'Phase',
      'Impact Level',
      'Notes',
      'Normalized Release Status',
      'Release Event',
      'Included Projects',
      'Included Bugs',
      'Included Stray Stories',
      'Known Issues',
      'Go / No-Go Required',
      'Decision Owner',
      'Primary Channel',
      'Slack Thread ID',
      'Current State Hash',
      'Previous State Hash',
      'Last Seen At',
      'Last Processed At',
      'Trigger Candidate',
      'Communication Event',
      'Dedupe Key',
      'Hub Queue ID',
      'Processing Status',
      'Processing Error'
    ],
    SNAPSHOTS: [
      'Snapshot ID',
      'Snapshot At',
      'Work Item Type',
      'Flow ID',
      'Source Row Key',
      'Source Sheet',
      'Source Row',
      'State Hash',
      'State JSON'
    ],
    TRIGGER_LOG: [
      'Trigger Log ID',
      'Created At',
      'Work Item Type',
      'Flow ID',
      'Source Row Key',
      'Trigger Candidate',
      'Communication Event',
      'Old State Hash',
      'New State Hash',
      'Old State Summary',
      'New State Summary',
      'Dedupe Key',
      'Hub Queue ID',
      'Processing Status',
      'Processing Error'
    ],
    CONFIG: ['Key', 'Value']
  },
  CONFIG_ROWS: [
    ['LEADERSHIP_SPREADSHEET_ID', ''],
    ['HUB_SPREADSHEET_ID', ''],
    ['PROJECTS_SOURCE_SHEET', 'Executive Dashboard'],
    ['GATES_SOURCE_SHEET', 'Executive Dashboard'],
    ['RELEASES_SOURCE_SHEET', 'Executive Dashboard'],
    ['PROJECTS_START_ROW', '3'],
    ['GATES_START_ROW', '24'],
    ['RELEASES_START_ROW', '57'],
    ['GATE_APPROACHING_DAYS', '14']
  ]
};

